# Select the base image
FROM python:3

# Install necessary packages
RUN pip install django
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/app
COPY . .

# Here we go
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

# docker build -t hello-django .
# docker run -it --rm -p 8000:8000 --name hello-django-running hello-django
