# Choosing a base image
FROM httpd:2.4

# copy your application files to the
# /usr/local/apache2/htdocs/ directory inside the container
WORKDIR /usr/local/apache2/htdocs/
COPY . .

# docker build -t hello-html .
# docker run -it --rm -p 80:80 --name hello-html-running hello-html